# simple dockerfile to test OCP s2i using Dockerfile 

FROM registry.access.redhat.com/ubi7:latest

#adeelanwer changing parameter of dockerfile to generate new output
#CMD ["/bin/bash", "-c", "sleep infinity"]
 CMD ["/bin/bash", "-c", "--", "while true; do sleep 30; done;"]
